name: "lidar"
driver:
  pkg: "sick_scan"
  ip: "192.168.1.112"
  port: "2112"
configuration:
  type: sick
  model: lms151
  rate: 50
  resolution: 0.5
geometry:
  parent_link: "base_link"
  xyz: [2.02, 0.0, 0.34]
  rpy: [0.0, 0.0, 0.0]
